HomeWork for Lesson17
Aston79/SauseDemo pull request #2
Opened 2021-12-02 19:58 UTC by Aston79

2021-12-02 20:47 UTC, mikola-2 requested changes

2021-12-02 20:47 UTC, mikola-2 commented on src/test/java/pages/BasePage.java
> +    public static final String URL = "https://www.saucedemo.com/";
Круто, что вынес, но нигде не используешь.

2021-12-02 20:47 UTC, mikola-2 commented on src/test/java/tests/ProductCriticalPathTest.java
> +        Assert.assertEquals(driver.findElement(By.cssSelector(PRODUCT_IN_THE_CART)).getText(), price, "Prices are not equal");
Тут ты сравниваешь имя продукта с его ценой. Вот, что я получил в результате упавшего теста:
```
java.lang.AssertionError: Prices are not equal 
Expected :$7.99
Actual   :Sauce Labs Onesie
```

2021-12-02 20:47 UTC, mikola-2 commented on src/test/java/tests/ProductCriticalPathTest.java
> +        Assert.assertEquals(driver.findElement(By.xpath(ADD_PRODUCT_CART_PRICE)), price, "Item prices not matched");
Тут ты сравниваешь веб элемент со строкой. Чтобы взять строку из веб элемента, следует у него взять метод .getText()

2021-12-02 20:47 UTC, mikola-2 commented on src/test/java/tests/ProductCriticalPathTest.java
> +        String price = inventoryPage.getPriceByName("Sauce Labs Onesie");
Брать значение цены со страницы инвентори лучше со страницы инвентори. В 47 строке ты уходишь с неё на страницу cart. Если строки 47 и 48 поменять местами, то будет логичнее.

2021-12-02 20:47 UTC, mikola-2 commented on src/test/java/tests/ProductCriticalPathTest.java
> +        Assert.assertFalse(Boolean.parseBoolean(ITEM_1), ITEM_2);
Не понимаю, что тут происходит. Значение в ассерт передаётся не из браузера, а значит и тестирования не происходит.

2021-12-02 21:44 UTC, Aston79 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
code
	{mso-style-priority:99;
	font-family:"Courier New";}
pre
	{mso-style-priority:99;
	mso-style-link:"\0421\0442\0430\043D\0434\0430\0440\0442\043D\044B\0439 HTML \0417\043D\0430\043A";
	margin:0cm;
	font-size:10.0pt;
	font-family:"Courier New";}
span.HTML
	{mso-style-name:"\0421\0442\0430\043D\0434\0430\0440\0442\043D\044B\0439 HTML \0417\043D\0430\043A";
	mso-style-priority:99;
	mso-style-link:"\0421\0442\0430\043D\0434\0430\0440\0442\043D\044B\0439 HTML";
	font-family:"Courier New";}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:2.0cm 42.5pt 2.0cm 3.0cm;}
div.WordSection1
	{page:WordSection1;}
-->Доброго времени суток! По поводу последнего замечания из списка -> поясняю следующее: в нижеприведенном Тесте введены две константы ITEM_1 и ITEM_2. Они принимают значение двух товаров находящихся рядом. Тест показывает, что в двух соседних блоках находятся разные товары, допустим очень внешне похожие.               Соответственно в разделе результатов тестирования указано (после внесенных исправлений), что товары разные.               Ввиду того, что полученные данные разные - тест успешен. Отправлено из приложения "Почта" для Windows От: Nikolay KudryashovОтправлено: четверг, 2 декабря 2021 г. в 23:47Кому: Aston79/SauseDemoКопия: Viktor; AuthorТема: Re: [Aston79/SauseDemo] HomeWork for Lesson17 (PR ***@***.*** requested changes on this pull request.In src/test/java/pages/BasePage.java:> @@ -0,0 +1,13 @@ +package pages; + +import org.openqa.selenium.WebDriver; + +public class BasePage { +    WebDriver driver; + +    public static final String URL = "https://www.saucedemo.com/"; Круто, что вынес, но нигде не используешь.In src/test/java/tests/ProductCriticalPathTest.java:> +import org.testng.Assert; +import org.testng.annotations.Test; + +import static pages.CartPage.PRODUCT_IN_THE_CART; +import static pages.InventoryPage.*; + +public class ProductCriticalPathTest extends BaseTest { + +    @Test +    public void productShouldBeAddedIntoCard() { +        loginPage.open(); +        loginPage.login("standard_user", "secret_sauce"); +        String price = inventoryPage.getPriceByName("Sauce Labs Onesie"); +        inventoryPage.addToCart("Sauce Labs Onesie"); +        cartPage.open(); +        Assert.assertEquals(driver.findElement(By.cssSelector(PRODUCT_IN_THE_CART)).getText(), price, "Prices are not equal"); Тут ты сравниваешь имя продукта с его ценой. Вот, что я получил в результате упавшего теста:java.lang.AssertionError: Prices are not equal  Expected :$7.99 Actual   :Sauce Labs Onesie In src/test/java/tests/ProductCriticalPathTest.java:> +    public void checkTheItemNameInTheCart() { +        loginPage.open(); +        loginPage.login("standard_user", "secret_sauce"); +        inventoryPage.addToCart("Sauce Labs Onesie"); +        cartPage.open(); +        Assert.assertEquals(driver.findElement(By.cssSelector(PRODUCT_IN_THE_CART)).getText(), "Sauce Labs Onesie", "Item names not matched"); +    } + +    @Test +    public void checkTheItemPriceInTheCart() { +        loginPage.open(); +        loginPage.login("standard_user", "secret_sauce"); +        inventoryPage.addToCart("Sauce Labs Onesie"); +        cartPage.open(); +        String price = inventoryPage.getPriceByName("Sauce Labs Onesie"); +        Assert.assertEquals(driver.findElement(By.xpath(ADD_PRODUCT_CART_PRICE)), price, "Item prices not matched"); Тут ты сравниваешь веб элемент со строкой. Чтобы взять строку из веб элемента, следует у него взять метод .getText()In src/test/java/tests/ProductCriticalPathTest.java:> +    @Test +    public void checkTheItemNameInTheCart() { +        loginPage.open(); +        loginPage.login("standard_user", "secret_sauce"); +        inventoryPage.addToCart("Sauce Labs Onesie"); +        cartPage.open(); +        Assert.assertEquals(driver.findElement(By.cssSelector(PRODUCT_IN_THE_CART)).getText(), "Sauce Labs Onesie", "Item names not matched"); +    } + +    @Test +    public void checkTheItemPriceInTheCart() { +        loginPage.open(); +        loginPage.login("standard_user", "secret_sauce"); +        inventoryPage.addToCart("Sauce Labs Onesie"); +        cartPage.open(); +        String price = inventoryPage.getPriceByName("Sauce Labs Onesie"); Брать значение цены со страницы инвентори лучше со страницы инвентори. В 47 строке ты уходишь с неё на страницу cart. Если строки 47 и 48 поменять местами, то будет логичнее.In src/test/java/tests/ProductCriticalPathTest.java:> + +    @Test +    public void checkTheItemPriceInTheCart() { +        loginPage.open(); +        loginPage.login("standard_user", "secret_sauce"); +        inventoryPage.addToCart("Sauce Labs Onesie"); +        cartPage.open(); +        String price = inventoryPage.getPriceByName("Sauce Labs Onesie"); +        Assert.assertEquals(driver.findElement(By.xpath(ADD_PRODUCT_CART_PRICE)), price, "Item prices not matched"); +    } + +    @Test +    public void checkItemNameTest() throws InterruptedException { +        loginPage.open(); +        loginPage.login("standard_user", "secret_sauce"); +        Assert.assertFalse(Boolean.parseBoolean(ITEM_1), ITEM_2); Не понимаю, что тут происходит. Значение в ассерт передаётся не из браузера, а значит и тестирования не происходит.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  

2021-12-03 07:42 UTC, mikola-2 requested changes

2021-12-03 07:42 UTC, mikola-2 commented on src/test/java/tests/ProductCriticalPathTest.java
> +        assertEquals(ITEM_1, ITEM_2, "Chosen items not the same");
Ты сравниваешь две константы, которые сам же и написал.
```
public static final String ITEM_1 = "//div[normalize-space()='Sauce Labs Bolt T-Shirt']";
public static final String ITEM_2 = "//div[normalize-space()='Sauce Labs Onesie']";
```
Как я вижу из кода, они точно не равны и тест упадёт. Тест же для проверок приложения пишем. Значит в актуальное значение нужно положить какой то текст, что берёшь из браузера. Как в 50 строке, что чуть выше.

2021-12-03 08:47 UTC, mikola-2 approved these changes

2021-12-03 08:47 UTC, mikola-2 commented on src/test/java/tests/ProductCriticalPathTest.java
> -    @Test
Тоже вариант)

2021-12-05 18:43 UTC, merged